// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://decotpugtobuavwdutyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlY290cHVndG9idWF2d2R1dHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mjk4MTIsImV4cCI6MjA2OTEwNTgxMn0.1b9x_I-WoiZx634vfTzO0-x_XYzuL1T3Vrr6hO4GgzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});